# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.20.5/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/nieyu/tempfile/macinfo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/nieyu/tempfile/macinfo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.20.5/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nieyu/tempfile/macinfo/CMakeFiles /Users/nieyu/tempfile/macinfo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/nieyu/tempfile/macinfo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cserial_static

# Build rule for target.
cserial_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cserial_static
.PHONY : cserial_static

# fast build rule for target.
cserial_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial_static.dir/build.make CMakeFiles/cserial_static.dir/build
.PHONY : cserial_static/fast

#=============================================================================
# Target rules for targets named macinfo

# Build rule for target.
macinfo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 macinfo
.PHONY : macinfo

# fast build rule for target.
macinfo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/build
.PHONY : macinfo/fast

#=============================================================================
# Target rules for targets named cserial

# Build rule for target.
cserial: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cserial
.PHONY : cserial

# fast build rule for target.
cserial/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial.dir/build.make CMakeFiles/cserial.dir/build
.PHONY : cserial/fast

c_serial.o: c_serial.c.o
.PHONY : c_serial.o

# target to build an object file
c_serial.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial_static.dir/build.make CMakeFiles/cserial_static.dir/c_serial.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/c_serial.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial.dir/build.make CMakeFiles/cserial.dir/c_serial.c.o
.PHONY : c_serial.c.o

c_serial.i: c_serial.c.i
.PHONY : c_serial.i

# target to preprocess a source file
c_serial.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial_static.dir/build.make CMakeFiles/cserial_static.dir/c_serial.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/c_serial.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial.dir/build.make CMakeFiles/cserial.dir/c_serial.c.i
.PHONY : c_serial.c.i

c_serial.s: c_serial.c.s
.PHONY : c_serial.s

# target to generate assembly for a file
c_serial.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial_static.dir/build.make CMakeFiles/cserial_static.dir/c_serial.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/c_serial.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cserial.dir/build.make CMakeFiles/cserial.dir/c_serial.c.s
.PHONY : c_serial.c.s

example_full.o: example_full.c.o
.PHONY : example_full.o

# target to build an object file
example_full.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/example_full.c.o
.PHONY : example_full.c.o

example_full.i: example_full.c.i
.PHONY : example_full.i

# target to preprocess a source file
example_full.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/example_full.c.i
.PHONY : example_full.c.i

example_full.s: example_full.c.s
.PHONY : example_full.s

# target to generate assembly for a file
example_full.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/macinfo.dir/build.make CMakeFiles/macinfo.dir/example_full.c.s
.PHONY : example_full.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cserial"
	@echo "... cserial_static"
	@echo "... macinfo"
	@echo "... c_serial.o"
	@echo "... c_serial.i"
	@echo "... c_serial.s"
	@echo "... example_full.o"
	@echo "... example_full.i"
	@echo "... example_full.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

